project:
  type: website
  title: "quarto-test"
  output-dir: _site
  render:
    - "*.qmd"

website:
  title: "Quarto test"
  
format:
  html:
    date: last-modified
    date-format: "DD-MMM-YYYY"
knitr:
  opts_chunk:
    fig-format: svg
    engine.opts:
      dvisvgm.opts: --font-format=woff
      template: tikzfig.tex

    
